In [1]:
# Core python libraries
import csv
import re
import math
import os
import time

# External libraries.
import nltk
import numpy
import pandas
import scipy
import sklearn
import tempfile

# Tensorflow and related.
import tensorflow as tf

# Plotting
import matplotlib.pyplot as plt

# So you know when this code block finishes.
print ("Done")

Done


In [2]:
#TODO(Max): make a library that does all this preprocessing
data = pandas.read_csv("data/train.csv") # Can read a subset. First nrows of the total.
LABEL_COLUMN = "SalaryNormalized"

TEST_SIZE = .3

print(len(data))

171482


In [3]:
# sklearn.cross_validation has been replaced with model_selection.
X_train_index, X_test_index, Y_train, Y_test = sklearn.model_selection.train_test_split(
    data.index, data[LABEL_COLUMN], test_size=TEST_SIZE, random_state=42)

# Keep train and test as pandas dataframes.
X_train = data.iloc[X_train_index]
X_test = data.iloc[X_test_index]

yb_train = numpy.array(X_train[LABEL_COLUMN].astype(numpy.float32))
yb_test= numpy.array(X_test[LABEL_COLUMN].astype(numpy.float32))

print ("Done")

Done


In [4]:
# Normalizing input values to mean 0, standard deviation 1.
train_mean, train_std = yb_train.mean(), yb_train.std()

def normalize_input(input_vector, train_mean, train_std):
    return (input_vector - train_mean)/train_std

def unnormalize_input(normalized_input_vector, train_mean, train_std):
    return (normalized_input_vector * train_std) + train_mean

# Move into a unit test.
test = numpy.arange(10)
test_mean, test_std = test.mean(), test.std()
print(test)
normed = normalize_input(test, test_mean, test_std)
print(normed)
unnormed = unnormalize_input(normed, test_mean, test_std)
print(unnormed)


# Normalize input labels and expectations
yb_train = normalize_input(yb_train, train_mean, train_std)
yb_test = normalize_input(yb_test, train_mean, train_std)


[0 1 2 3 4 5 6 7 8 9]
[-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [62]:
print(train_std)
print(yb_test)

17698.3
[ 0.89645004 -0.66550416  3.22435188 ..., -0.29010177  0.89645004
  0.95295256]


In [6]:
target_column = "CompleteJobListingStemmed"

x_train_text = X_train[target_column]
x_test_text = X_test[target_column]

max_document_length = max([len(x.split(" ")) for x in x_train_text])

In [7]:
# Look here for a tutorial https://medium.com/@ilblackdragon/tensorflow-text-classification-615198df9231
min_word_frequency = 75

vocab_processor = tf.contrib.learn.preprocessing.VocabularyProcessor(
    max_document_length, min_frequency=min_word_frequency)
x_train = numpy.array(list(vocab_processor.fit_transform(x_train_text)))
print("x_train shape: %s, %s" % x_train.shape)
x_test = numpy.array(list(vocab_processor.transform(x_test_text)))
print("x_test shape: %s, %s" % x_test.shape)
n_words = len(vocab_processor.vocabulary_)
print("Total distinct words: %d" % n_words)

# Try looking at https://github.com/nfmcclure/tensorflow_cookbook/blob/master/07_Natural_Language_Processing/02_Working_with_Bag_of_Words/02_bag_of_words.py


x_train shape: 120037, 1368
x_test shape: 51445, 1368
Total distinct words: 8712


In [58]:
print(len(x_train))

137108


In [53]:
# Function to generate a training batch.

# Are these breaking past a certain point?
def generate_batch(batch_size, number_of_batches, input_data, input_labels):
    """Give me a docstring to explain."""
    batch = numpy.ndarray(shape=(batch_size, max_document_length),
                          dtype=numpy.int32)
    labels = numpy.ndarray(shape=(batch_size, 1), dtype=numpy.float32)
    
    batch_index = 0
    while batch_index < number_of_batches:
        for element_index in range(batch_size):
            # Prevents overflow.
            data_index = ((batch_index * batch_size) + element_index) % len(input_data)
            batch[element_index] = numpy.array(input_data[data_index])
            labels[element_index] = input_labels[data_index]
        batch_index += 1
        yield batch, labels
    

def input_fn():
    for batch_input, batch_labels in generate_batch(batch_size, number_of_batches,
                                                    x_train, yb_train):
        yield {x_data: batch_input, y_target: batch_labels}

def eval_input_fn():
    for batch_input, batch_labels in generate_batch(batch_size, number_of_validation_batches,
                                                    x_test, yb_test):
        yield {x_data: batch_input, y_target: batch_labels}


In [72]:
graph = tf.Graph()

sess = tf.Session(graph=graph)

learning_rate = .05

l1_regularization_coef = 0.01
l2_regularization_coef = 0.0

momentum = None

# Sklearn shuffles after epoch by default.

# if not RMSE then MAE.
HUBER = True
RMSE = False

#Implement this by batch.
batch_size = 32

#Size of input dictionary. Number of distinct words.
vocab_size = len(vocab_processor.vocabulary_)

def huber_loss(labels, predictions, delta=1.0):
 residual = tf.abs(predictions - labels)
 condition = tf.less(residual, delta)
 small_res = 0.5 * tf.square(residual)
 large_res = delta * residual - 0.5 * tf.square(delta)
 return tf.reduce_mean(tf.where(condition, small_res, large_res))

with graph.as_default():

    # Setup Index Matrix necessary for one-hot-encoding
    identity_mat = tf.diag(tf.ones(shape=[vocab_size]))

    # Create variables for regression
    A = tf.Variable(tf.random_normal(shape=[vocab_size, 1]))

    # Intercept term. A scalar.
    b = tf.Variable(tf.random_normal(shape=[1]))

    # Initialize data placeholders
    x_data = tf.placeholder(shape=[batch_size, max_document_length], dtype=tf.int32)
    y_target = tf.placeholder(shape=[batch_size, 1], dtype=tf.float32, name="labels")

    # Text-Vocab Embedding
    # x_embed has rows equal to max_document_length, and columns equal to
    # The number of distinct word tokens
    # This is also an embedding_lookup_sparse function that would create a sparse tensor.
    x_embed = tf.nn.embedding_lookup(identity_mat, x_data)
    # Collapse accross the document length dimension. Leaving only the number of tokens.
    x_col_sums = tf.reduce_sum(x_embed, 1)
    print("Woohoo this looks like my bag of words shape :D %s" % x_col_sums.shape)

    # Model output
    product = tf.matmul(x_col_sums, A)
    model_output = tf.add(product, b, name="predictions")

    # TODO(Max) try root mean square error. Should this be merely mean square error?
    if HUBER:
        loss = huber_loss(y_target, model_output)
    elif RMSE:
        loss = tf.sqrt(tf.reduce_mean(tf.pow(tf.subtract(y_target, model_output), 2)))
    else:
        # Mean Absolute Error.
        loss = tf.reduce_mean(tf.abs(tf.subtract(y_target, model_output)))
    
    # If we are using regularization.
    if l1_regularization_coef > 0 or l2_regularization_coef > 0:
        l1_regularizer = tf.contrib.layers.l1_regularizer(scale=l1_regularization_coef)
        l2_regularizer = tf.contrib.layers.l2_regularizer(scale=l2_regularization_coef)
    
        weights = tf.trainable_variables() # all vars of your graph
        regularization_penalty = tf.add(tf.contrib.layers.apply_regularization(l1_regularizer, weights),
                                         tf.contrib.layers.apply_regularization(l2_regularizer, weights))
        loss = loss + regularization_penalty # this loss needs to be minimized

    
    # Converts back to original, salary scale.
    error_salary_scale = tf.multiply(tf.subtract(y_target, model_output), train_std)
    
    mean_absolute_error_salary_scale = tf.reduce_mean(
        tf.abs(error_salary_scale))

    # Log for tensorboard
    training_summary = tf.summary.scalar('train_loss', loss)
    validation_summary = tf.summary.scalar('validation_loss', loss)
    # Add mean absolute errors.
    training_mae = tf.summary.scalar('train_mae', mean_absolute_error_salary_scale)
    validation_mae = tf.summary.scalar('validation_mae', mean_absolute_error_salary_scale)

    global_step = tf.Variable(0, name='global_step', trainable=False)

    # Declare optimizer
    if momentum is None:
        optimizer = tf.train.GradientDescentOptimizer(learning_rate)
    
    if momentum is not None:
       optimizer = tf.train.MomentumOptimizer(learning_rate, momentum)
    
    # This one seems to work better :D
    train_op = tf.contrib.layers.optimize_loss(      
     loss, tf.contrib.framework.get_global_step(),      
     optimizer='Adam'
        , learning_rate=learning_rate, clip_gradients=1.0)


Woohoo this looks like my bag of words shape :D (32, 8712)
INFO:tensorflow:Scale of 0 disables regularizer.


In [37]:
# Number of
number_of_epochs = 10
batches_per_epoch = len(x_train_text)/batch_size
number_of_batches = math.ceil(len(x_train_text)/batch_size)
number_of_validation_batches = number_of_batches

logs_dir = "logs/bagofwords"

checkpoint_frequency = 250

reporting_frequency = 3

total_loss = 0
validation_loss = 0
validation_batch_average_window = 100

model_path = os.path.join(logs_dir, time.strftime("%Y-%m-%d-%H-%M-%S"))

ckpt = None
ckpt = tf.train.get_checkpoint_state(logs_dir)                                     

if ckpt:
    restore_from_model = True
    print("Restore from model!")
else:
    restore_from_model = False

with tf.Session(graph=graph, config=tf.ConfigProto(
    allow_soft_placement=True, log_device_placement=True)) as session:
    summaries = tf.summary.merge_all()                                                       
    writer = tf.summary.FileWriter(model_path,
        graph=session.graph)                  

    saver = tf.train.Saver(tf.global_variables()) 
                                                                                                  
    session.run(tf.global_variables_initializer())
    
    
    if restore_from_model:
        saver.restore(session, ckpt.model_checkpoint_path)
        
    for epoch in range(number_of_epochs):
        eval_feed_generator = eval_input_fn()

        for step, feed_dict in enumerate(input_fn()):
            start_time = time.time()

            _, temp_loss = session.run([train_op, loss], feed_dict=feed_dict)
            
            duration = time.time() - start_time

            total_loss += temp_loss
            if (step + 1) % reporting_frequency == 0:
                print("Epoch: %s Training Observation: %s : Mean Loss: %.4f (%.3f sec)" % (epoch, (step + 1), total_loss/reporting_frequency, duration))
                print(b.eval())
                total_loss = 0
                train_summ, train_mae = session.run([training_summary, training_mae], feed_dict=feed_dict)
                writer.add_summary(train_summ, step)
                writer.add_summary(train_mae, step)

                _, valid_summ, valid_mae = session.run(
                    [loss, validation_summary, validation_mae],
                    feed_dict=next(eval_feed_generator))
                writer.add_summary(valid_summ, step)
                writer.add_summary(valid_mae, step)
                
                writer.flush()                

            if ((step + 1) % checkpoint_frequency == 0) or (step + 1 == number_of_batches):
                print("Saving at epoch %s step: %s" % (epoch, step + 1))
                saver.save(session, model_path, global_step=tf.contrib.framework.get_global_step())

    



Restore from model!
INFO:tensorflow:Restoring parameters from logs/bagofwords/2017-06-11-18-06-00-1750
Epoch: 0 Training Observation: 3 : Mean Loss: 6.3697 (0.964 sec)
[-0.00208002]
Epoch: 0 Training Observation: 6 : Mean Loss: 6.4061 (0.940 sec)
[ 0.00446413]
Epoch: 0 Training Observation: 9 : Mean Loss: 6.5499 (0.960 sec)
[-0.00241382]
Epoch: 0 Training Observation: 12 : Mean Loss: 6.3353 (1.012 sec)
[ 0.00382377]
Epoch: 0 Training Observation: 15 : Mean Loss: 6.6694 (0.972 sec)
[-0.00334767]
Epoch: 0 Training Observation: 18 : Mean Loss: 6.0642 (1.043 sec)
[ 0.00306244]
Epoch: 0 Training Observation: 21 : Mean Loss: 7.0035 (0.978 sec)
[-0.0039469]
Epoch: 0 Training Observation: 24 : Mean Loss: 6.2509 (0.970 sec)
[ 0.00221835]
Epoch: 0 Training Observation: 27 : Mean Loss: 7.0107 (0.962 sec)
[-0.00484772]
Epoch: 0 Training Observation: 30 : Mean Loss: 6.0442 (1.036 sec)
[ 0.00159589]
Epoch: 0 Training Observation: 33 : Mean Loss: 6.8936 (0.968 sec)
[-0.00514283]
Epoch: 0 Training Obs

KeyboardInterrupt: 

In [66]:
# How much data to evaluate
#number_of_batches = len(x_train_text)/batch_size
number_of_validation_batches = len(x_test_text)/batch_size
ckpt = tf.train.get_checkpoint_state(logs_dir)                                     


# Write TF Model Evaluation Code here. 
with tf.Session(graph=graph, config=tf.ConfigProto(
    allow_soft_placement=True, log_device_placement=True)) as session:
    
    saver = tf.train.Saver(tf.global_variables()) 
                                                                                                  
    session.run(tf.global_variables_initializer())
    
    saver.restore(session, ckpt.model_checkpoint_path)

    
    total_loss = 0
    for step, eval_feed_dict in enumerate(eval_input_fn()):
        #print(model_output.eval(eval_feed_dict))
    
        valid_loss, check = session.run([loss, model_output], feed_dict=eval_feed_dict)
        #print(valid_loss)
        print(check)
        #total_loss += valid_loss[0]
    print (total_loss/step)

INFO:tensorflow:Restoring parameters from logs/bagofwords/2017-06-11-18-50-07-2750
[[ 7.62809706]
 [ 5.58852959]
 [ 5.59177494]
 [ 4.19827127]
 [ 4.77808237]
 [ 4.40655136]
 [ 5.71067286]
 [ 5.22041607]
 [ 6.01734018]
 [ 5.10449934]
 [ 5.30105305]
 [ 3.81013751]
 [ 6.34175777]
 [ 5.82009935]
 [ 3.93765473]
 [ 5.24715519]
 [ 4.14017725]
 [ 5.00824213]
 [ 2.93639183]
 [ 9.80047035]
 [ 5.68838787]
 [ 5.69848299]
 [ 4.90348387]
 [ 4.14938688]
 [ 0.48562685]
 [ 6.66180992]
 [ 6.97311687]
 [ 5.20588207]
 [ 5.91129065]
 [ 5.41713524]
 [ 5.55389643]
 [ 4.1693902 ]]
[[ 4.40772581]
 [ 4.85887718]
 [ 5.63510847]
 [ 4.16571617]
 [ 3.0416162 ]
 [ 5.06451511]
 [ 7.68068266]
 [ 8.1142025 ]
 [ 4.6945343 ]
 [ 2.70778513]
 [ 2.93298984]
 [ 5.79860401]
 [ 4.44708443]
 [ 6.07296944]
 [ 5.85468292]
 [ 3.97273922]
 [ 5.29035854]
 [ 5.34177971]
 [ 4.53326225]
 [ 5.20281601]
 [ 3.1871531 ]
 [ 5.94475555]
 [ 3.72513795]
 [ 1.50133336]
 [ 7.20599651]
 [ 3.39951134]
 [ 2.5661459 ]
 [ 3.28695846]
 [ 5.98905182]
 

KeyboardInterrupt: 

In [75]:
#model_output.eval()
eval_generator = eval_input_fn()

with sess:
    saver = tf.train.Saver(tf.global_variables())                                                                                               
    sess.run(tf.global_variables_initializer())
    sess.run(model_output, feed_dict=next(eval_generator))

RuntimeError: Attempted to use a closed Session.

In [114]:
%matplotlib inline

def print_results(model):
    y_vals = [value for value in model.predict(input_fn=eval_input_fn)]
    x_vals = X_test[LABEL_COLUMN]


    plt.scatter(x_vals, y_vals)
    plt.show()

    print(x_vals-y_vals)
    #print(sorted([set(y_vals)]))

    print("Mean absolute error: %s" % 
          mean_absolute_error_salary_scale(y_vals, x_vals))
    
    
print_results(m)

Instructions for updating:
Please switch to predict_scores, or set `outputs` argument.


NotFittedError: Couldn't find trained model at /tmp/tmpc4vvis3j.